Headers:
  TestResult:
    PrintCount: 2
    Title: "{}回目"
    Labels:
      - 実施担当
      - 確認担当
      - 実施日
      - 結果
  TestItemsLabel:
    - ステップ
    - 中項目
    - 小項目
    - 詳細項目
  BackColor: "002060"
  TextColor: "FFFFFF"
Sheet:
  Name: "試験票"
  Caption: "テスト一覧"
  FontName: "游ゴシック"
  FontSize: 14
  Height: 18.75
ColumnSet:
  Common:
    Header:
      FontName: "游ゴシック"
      FontSize: 10
      FontColor: "FFFFFF"
      AlignVertical: top
      AlignHorizontal: center
    Body:
      FontName: "游ゴシック"
      FontSize: 10
      AlignVertical: top
      AlignHorizontal: left
      AlignWrapText: True
  "No":
    Header:
      Replace: "No."
      AlignHorizontal: left
    Body:
      Replace: "=ROW()-3"
  ステップ:
    Header:
      AlignHorizontal: left
      Replace: STEP
  中項目:
    Header:
      AlignHorizontal: left
  小項目:
    Header:
      AlignHorizontal: left
  詳細項目:
    Header:
      AlignHorizontal: left
  実施担当:
    Header:
      Replace: |-
        実施
        担当
      Width: 4.25
      AlignWrapText: true
  確認担当:
    Header:
      Replace: |-
        確認
        担当
      Width: 4.25
      AlignWrapText: true
  実施日:
    Header:
      Width: 9
    Body:
      FontSize: 8
  結果:
    Header:
      Width: 4.25
  TestResultHeader:
    AlignVertical: center
    AlignHorizontal: center
    Height: 24
  HeaderRow:
    Height: 36
